fetch data from API
gitboej/capstone-project pull request #5
Opened 2023-05-23 14:34 UTC by gitboej

2023-05-23 15:39 UTC, ThomasKirst requested changes
Hi Lars,
great that you connected the API. I just found an issue with the API key and left you a comment.
– Thomas

2023-05-23 15:39 UTC, ThomasKirst commented on pages/index.js
> +        "https://api.polygon.io/v2/aggs/grouped/locale/global/market/crypto/2023-05-22?apiKey=tgmy3Uasr3HfP7yyZ6UmwslF9LiHoGjr"
It is not recommended to expose API keys in client-side code, as it can be easily accessed by anyone who inspects the code. A better approach would be to store the API key in a server-side environment variable and make the API request from the server. The server can then return the data to the client. This way, the API key is not exposed to the client-side code and is kept secure.

Move the API key to an `env.local` file:
`API_KEY=tgmy...`

Then you create an API route in Next.js which does the actual fetch and returns the result to the client.
```js
// pages/api/crypto.js

export default async function handler(req, res) {
  const { API_KEY } = process.env;
  const response = await fetch(`https://api.polygon.io/v2/aggs/grouped/locale/global/market/crypto/2023-05-22?apiKey=${API_KEY}`);
  // Get the json of the response and return the data
  // Also consider adding error handling
  res.status(200).json(data);
}
```

In your frontend (in /pages/index.js) you would no longer fetch the crypto API directly, but fetch your own API Route instead (`/api/crypto`).

For further questions you can contact Niklas tomorrow ;)

2023-05-25 13:53 UTC, gitboej commented on pages/index.js
> +        "https://api.polygon.io/v2/aggs/grouped/locale/global/market/crypto/2023-05-22?apiKey=tgmy3Uasr3HfP7yyZ6UmwslF9LiHoGjr"
Thanks for your feedback :)

2023-05-25 13:59 UTC, ThomasKirst approved these changes
Works great!

2026-06-04 15:42 UTC, merged